Dict = {}
f1 = input("Enter name of the 1st friend")
l1 = input("Enter favourite language of the 1st friend")
f2 = input("Enter name of the 2nd friend")
l2 = input("Enter favourite language of the 2nd friend")
f3 = input("Enter name of the 3rd friend")
l3 = input("Enter favourite language of the 3rd friend")
f4 = input("Enter name of the 4th friend")
l4 = input("Enter favourite language of the 4th friend")
Dict.update({f1: l1})
Dict.update({f2: l2})
Dict.update({f3: l3})
Dict.update({f4: l4})
print(Dict)