a = 9  # Integer
print("a = ", type(a))
b = "Aditya"  # Anything inside quote, it's considered a string
# b = 'Aditya' # String
# b = '''Aditya''' # For multi-line
print("b = ", type(b))
c = "99.39"  # String since inside double quote
print("c = ", type(c))
d = 44.23  # Float
print("d = ", type(d))
e = True  # Boolean or bool
print("e = ", type(e))
f = None  # None OR null
print("f = ", type(f))
