# Arithmetic Operator
print("Sum of 7 and 5 is :", 7+5)
print("Diff of 7 and 5 is :", 7-5)
print("Mul of 7 and 5 is :", 7*5)
print("Div of 7 and 5 is :", 7/5)

# Assignment Operator
a = 11
a -= 4
a *= 3
a /= 2  # Output a float
print(a)

# Comaprison Operators # Output a boolean
a = (5 > 9)
print(a)
a = (3 == 3)
print(a)
a = (3 < 7)
print(a)

# Logical Operators
bool1 = True
bool2 = False
print("The value of bool1 and bool2 is ", (bool1 and bool2))  # Implies 'and'
print("The value of bool1 or bool2 is ", (bool1 or bool2))  # Implies 'or'
print("The value of not bool2 is ", (not bool2))  # Opposite
print("The value of not bool1 is ", (not bool1))  # Opposite
